// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMA.Api;

#nullable disable

namespace TMA.Api.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20241106095846_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("TMA.Api.Model.Actions", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionId");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            ActionName = "Create",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5814)
                        },
                        new
                        {
                            ActionId = 2,
                            ActionName = "Edit",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5816)
                        },
                        new
                        {
                            ActionId = 3,
                            ActionName = "Delete",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5817)
                        },
                        new
                        {
                            ActionId = 4,
                            ActionName = "View",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5818)
                        });
                });

            modelBuilder.Entity("TMA.Api.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5775),
                            IsDeleted = false,
                            Name = "Admin",
                            RoleDescription = "Administrator with full access"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5789),
                            IsDeleted = false,
                            Name = "Manager",
                            RoleDescription = "Manager with limited management rights"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5790),
                            IsDeleted = false,
                            Name = "User",
                            RoleDescription = "Standard user with read-only access"
                        });
                });

            modelBuilder.Entity("TMA.Api.Model.RoleAction", b =>
                {
                    b.Property<int>("RoleActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFullAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleActionId");

                    b.HasIndex("ActionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleActions");

                    b.HasData(
                        new
                        {
                            RoleActionId = 1,
                            ActionId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5840),
                            HasFullAccess = true,
                            HasReadOnly = false,
                            RoleId = 1
                        },
                        new
                        {
                            RoleActionId = 2,
                            ActionId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5843),
                            HasFullAccess = true,
                            HasReadOnly = false,
                            RoleId = 1
                        },
                        new
                        {
                            RoleActionId = 3,
                            ActionId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5846),
                            HasFullAccess = true,
                            HasReadOnly = false,
                            RoleId = 1
                        },
                        new
                        {
                            RoleActionId = 4,
                            ActionId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5847),
                            HasFullAccess = true,
                            HasReadOnly = false,
                            RoleId = 1
                        },
                        new
                        {
                            RoleActionId = 5,
                            ActionId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5849),
                            HasFullAccess = false,
                            HasReadOnly = false,
                            RoleId = 2
                        },
                        new
                        {
                            RoleActionId = 6,
                            ActionId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5909),
                            HasFullAccess = false,
                            HasReadOnly = false,
                            RoleId = 2
                        },
                        new
                        {
                            RoleActionId = 7,
                            ActionId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5911),
                            HasFullAccess = false,
                            HasReadOnly = true,
                            RoleId = 2
                        },
                        new
                        {
                            RoleActionId = 8,
                            ActionId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2024, 11, 6, 15, 28, 46, 494, DateTimeKind.Local).AddTicks(5913),
                            HasFullAccess = false,
                            HasReadOnly = true,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TMA.Api.Model.Tasks", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TMA.Api.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Admin St",
                            City = "Admin City",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5484),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            Password = "Admin@123",
                            PhoneNumber = "123-456-7890",
                            UserStatusId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Manager Ave",
                            City = "Manager City",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5490),
                            Email = "manager@example.com",
                            FirstName = "Manager",
                            IsDeleted = false,
                            LastName = "User",
                            Password = "Manager@123",
                            PhoneNumber = "987-654-3210",
                            UserStatusId = 1
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 User Blvd",
                            City = "User City",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5492),
                            Email = "user@example.com",
                            FirstName = "Regular",
                            IsDeleted = false,
                            LastName = "User",
                            Password = "User@123",
                            PhoneNumber = "555-555-5555",
                            UserStatusId = 1
                        });
                });

            modelBuilder.Entity("TMA.Api.Model.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5741),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserRoleId = 2,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5743),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            UserRoleId = 3,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 11, 6, 9, 58, 46, 494, DateTimeKind.Utc).AddTicks(5744),
                            RoleId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TMA.Api.Model.RoleAction", b =>
                {
                    b.HasOne("TMA.Api.Model.Actions", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMA.Api.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TMA.Api.Model.UserRole", b =>
                {
                    b.HasOne("TMA.Api.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMA.Api.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
